### ISSUE TITLE
Gutter causes gap in highlighted line

### ISSUE THREAD

**Issue by dsandstrom** [steelbrain/linter#1151]
When we use a theme that highlights the current line, the linter gutter causes a gap.

![00000177](https://cloud.githubusercontent.com/assets/1400414/15261773/2c337968-1913-11e6-836a-e7abc81462a2.png)

A simple fix is to make the linter's gutter absolute positioned:
```less
atom-text-editor::shadow .gutter[gutter-name="linter"] {
  position: absolute;
  right: 0;
  background-color: transparent;

  .custom-decorations {
    background-color: transparent !important;
  }
}
```
I couldn't figure out when/why this change occurred.  I think the change happened upstream because I tried older versions of this package.

**Comment by dsandstrom** [comment]
Updated styles:
```less
atom-text-editor::shadow .gutter-container {
  position: relative;
}

atom-text-editor::shadow .gutter[gutter-name="linter"] {
  position: absolute;
  right: 0;
  bottom: 0;
  top: 0;
  background-color: transparent;

  .custom-decorations {
    background-color: transparent !important;
  }
}
```
I forgot to mention the container needs to be relatively position.  Also, I added a fix for the dots being overlayed on top of the search pane.
