### ISSUE TITLE
Git-diff Style issues on Deleted

### ISSUE THREAD

**Issue by deybhayden** [steelbrain/linter#202]
**Package Detail**

Atom: 0.124.0
git-diff: 0.39.0
Linter: 0.5.17

**Problem**

When I delete code in the editor with both packages on (but with git diff icons off), I get the below style issue:

![screen shot 2014-09-03 at 5 02 18 pm](https://cloud.githubusercontent.com/assets/877908/4142195/37018e3c-33b6-11e4-823e-5f7f10149d51.png)

My temporary workaround is the below LESS in which I hacked from another reported git-diff issue in #121.

``` css
 /* Override git-diff for linter */
 .editor .gutter .line-number.git-line-removed {
     padding-left: 1.5em;
     &:before {
         visibility: visible !important;
     }
 }
```
